name: Enhancement Request
description: Request new features 
title: '[Enhancement]:'
labels: ["enhancement"]
projects: ["ziphius-labs/7"]
assignees: []

body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Feature requests are unlikely to make progress as issues. Please consider engaging with SIGs on slack and mailing lists, instead.
        A proposal that works through the design along with the implications of the change can be opened as a KEP.
        See https://git.k8s.io/enhancements/keps#kubernetes-enhancement-proposals-keps
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true